global:
  scrape_interval: 5s
  scrape_timeout: 3s

scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: ['localhost:9100']

  - job_name: 'server'
    static_configs:
      - targets: ['localhost:9200']
